In [14]:
import torch as tc

In [15]:
x = tc.empty(1)
print(x)

tensor([7.5431e-35])


In [16]:
x = tc.empty(3)
print(x)

tensor([7.6697e-35, 0.0000e+00, 1.1139e+12])


In [17]:
x = tc.empty(3, 3)
print(x)

tensor([[7.5351e-35, 0.0000e+00, 7.4710e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00],
        [1.3452e-43, 0.0000e+00, 3.8941e-41]])


In [18]:
x = tc.empty(3, 3, 2)
print(x)

tensor([[[1.1139e+12, 4.5768e-41],
         [7.5074e-35, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [7.7052e+31, 7.2148e+22]],

        [[1.5766e-19, 1.0256e-08],
         [4.1019e-08, 3.1128e+12],
         [1.0838e-08, 1.0564e-05]]])


In [19]:
x = tc.rand(3, 3)
print(x)

tensor([[0.4082, 0.4590, 0.7323],
        [0.1899, 0.7449, 0.8995],
        [0.2669, 0.9668, 0.7359]])


In [20]:
x = tc.zeros(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
x = tc.ones(3, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [22]:
x = tc.ones(3, 3, dtype=tc.int16)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [24]:
A = [2.5, 0.1]
x = tc.tensor(A)
print(x)

tensor([2.5000, 0.1000])


In [27]:
x = tc.ones(2, 2)
y = tc.rand(2, 2)

print(x)
print(y)

z = x * y

print(z)

z = tc.mul(x, y)

print(z)

z = tc.add(x, y)

print(z)

z = tc.sub(x, y)

print(z)

z = tc.div(x, y)

print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0905, 0.8244],
        [0.0990, 0.1388]])
tensor([[0.0905, 0.8244],
        [0.0990, 0.1388]])
tensor([[0.0905, 0.8244],
        [0.0990, 0.1388]])
tensor([[1.0905, 1.8244],
        [1.0990, 1.1388]])
tensor([[0.9095, 0.1756],
        [0.9010, 0.8612]])
tensor([[11.0452,  1.2131],
        [10.1050,  7.2036]])


In [31]:
x = tc.rand(5, 3)
print(x)

tensor([[0.0825, 0.8019, 0.4633],
        [0.1434, 0.1692, 0.3548],
        [0.5017, 0.0723, 0.0502],
        [0.3941, 0.3611, 0.3092],
        [0.7938, 0.0959, 0.1476]])
tensor([0.0825, 0.1434, 0.5017, 0.3941, 0.7938])
tensor([0.0825, 0.8019, 0.4633])


In [32]:
print(x[:, 0])

tensor([0.0825, 0.1434, 0.5017, 0.3941, 0.7938])


In [33]:
print(x[0, :])

tensor([0.0825, 0.8019, 0.4633])


In [34]:
print(x[0, 0].item())

0.08253055810928345


In [37]:
x = tc.rand(4, 4)
print(x)

tensor([[0.3415, 0.4207, 0.8087, 0.0226],
        [0.2099, 0.4521, 0.7605, 0.7816],
        [0.1458, 0.9844, 0.1183, 0.1748],
        [0.8024, 0.7438, 0.2740, 0.0122]])


In [42]:
y = x.flatten()
print(y)

tensor([0.3415, 0.4207, 0.8087, 0.0226, 0.2099, 0.4521, 0.7605, 0.7816, 0.1458,
        0.9844, 0.1183, 0.1748, 0.8024, 0.7438, 0.2740, 0.0122])


In [38]:
y = x.view(16)
print(y)

tensor([0.3415, 0.4207, 0.8087, 0.0226, 0.2099, 0.4521, 0.7605, 0.7816, 0.1458,
        0.9844, 0.1183, 0.1748, 0.8024, 0.7438, 0.2740, 0.0122])


In [39]:
y = x.view(2, 8)
print(y)

tensor([[0.3415, 0.4207, 0.8087, 0.0226, 0.2099, 0.4521, 0.7605, 0.7816],
        [0.1458, 0.9844, 0.1183, 0.1748, 0.8024, 0.7438, 0.2740, 0.0122]])


In [41]:
y = x.view(-1, 2)
print(y)

tensor([[0.3415, 0.4207],
        [0.8087, 0.0226],
        [0.2099, 0.4521],
        [0.7605, 0.7816],
        [0.1458, 0.9844],
        [0.1183, 0.1748],
        [0.8024, 0.7438],
        [0.2740, 0.0122]])
