In [3]:
import torch as tc
import numpy as np

In [4]:
a = np.array([0.5, 0.2, 2])

print(a)

[0.5 0.2 2. ]


In [5]:
b = tc.tensor(a)

print(b)

tensor([0.5000, 0.2000, 2.0000], dtype=torch.float64)


In [6]:
a = tc.ones(5)

print(a)

tensor([1., 1., 1., 1., 1.])


In [7]:
b = a.numpy()

print(b)

[1. 1. 1. 1. 1.]


In [8]:
tc.cuda.is_available()

True

In [9]:
if tc.cuda.is_available():
    device = tc.device("cuda")
    x = tc.ones(5, device=device)

    print(x)

    x = x.to("cpu")

    print(x)

    z = x.numpy()

    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
